global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'API'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['VideoGameAPI1:8080', 'VideoGameAPI2:8080', 'VideoGameAPI3:8080']

  - job_name: 'Prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'Kakfa'
    static_configs:
      - targets: ['VideoGameKafka:1099']

  - job_name: 'Nginx'
    static_configs:
      - targets: ['VideoGameNginxExporter:9113']

  - job_name: 'Advanced Nginx'
    static_configs:
      - targets: ['VideoGameTelegraf:9125'] 

  - job_name: 'Email Server'
    static_configs:
      - targets: ['VideoGameEmailServer:3000']

  - job_name: 'MySQL'
    metrics_path: /probe
    params:
      auth_module: [client.servers]
    static_configs:
      - targets:
        - VideoGameDB:3306
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: VideoGameMySQLExporter:9104

