global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'API'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['VideoGameAPI1:8080', 'VideoGameAPI2:8080', 'VideoGameAPI3:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'kakfa'
    static_configs:
      - targets: ['VideoGameKafka:1099']


